spring.application.name=spring-boot-mvc
spring.thymeleaf.enabled=true
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.reactive.max-chunk-size=8192
spring.thymeleaf.allow-empty-template=true
spring.messages.basename=messages,labels,errors
spring.messages.encoding=UTF-8
spring.thymeleaf.check-template=true
spring.thymeleaf.enable-spring-el-compiler=true
spring.thymeleaf.restrict-javascript-inline=true
spring.thymeleaf.reactive.response-timeout=5000
spring.thymeleaf.reactive.chunked-mode-view-names=*
logging.level.org.thymeleaf=DEBUG
logging.level.org.thymeleaf.TemplateEngine=TRACE

# Database Configuration H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect